"use client";

import { useQueryClient } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import * as React from "react";
import type { DocumentSource, TradeDocumentType } from "@exportpro/types";
import { DOCUMENT_SOURCES, RESPONSIBLE_PARTIES, TRADE_DOCUMENT_TYPES } from "@exportpro/types";
import { documentsApi } from "@/lib/api/compliance";
import { ApiRequestError, toFriendlyErrorMessage } from "@/lib/api-client";
import { DOC_TYPE, PARTY, SOURCE } from "@/lib/compliance-labels";
import { toast } from "@/lib/toast";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Modal } from "@/components/ui/modal";
import { Progress } from "@/components/ui/progress";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Caption } from "@/components/ui/typography";

const ACCEPT = ".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx,.csv,.txt";
const EXTERNAL_SOURCES = DOCUMENT_SOURCES.filter((s) => s !== "SYSTEM_GENERATED");

export interface UploadDefaults {
  documentType?: TradeDocumentType;
  allowedTypes?: TradeDocumentType[];
  purchaseOrderId?: string;
  requirementId?: string;
  requirementName?: string;
  replacesDocumentId?: string;
}

/** Upload (or record by reference) an external/official document. Never labelled as generated by ExportPro. */
export function UploadDocumentDialog({ open, onClose, defaults }: { open: boolean; onClose: () => void; defaults: UploadDefaults }) {
  const router = useRouter();
  const qc = useQueryClient();
  const types = defaults.allowedTypes?.length ? defaults.allowedTypes : TRADE_DOCUMENT_TYPES;
  const [f, setF] = React.useState({ documentType: defaults.documentType ?? types[0], source: "GOVERNMENT_ISSUED" as DocumentSource, responsibleParty: "GOVERNMENT", documentNumber: "", issuer: "", issueDate: "", expiryDate: "", notes: "" });
  const [file, setFile] = React.useState<File | null>(null);
  const [referenceOnly, setReferenceOnly] = React.useState(false);
  const [progress, setProgress] = React.useState(0);
  const [busy, setBusy] = React.useState(false);
  const [duplicate, setDuplicate] = React.useState<string | null>(null);
  const set = (k: keyof typeof f, v: string) => setF((p) => ({ ...p, [k]: v }));
  const submit = async (allowDuplicate = false) => {
    setBusy(true);
    const fields = { ...f, purchaseOrderId: defaults.purchaseOrderId, requirementId: defaults.requirementId, replacesDocumentId: defaults.replacesDocumentId, allowDuplicate: allowDuplicate ? "true" : undefined };
    const clean = Object.fromEntries(Object.entries(fields).filter(([, v]) => v)) as Record<string, string>;
    try {
      const d = referenceOnly ? await documentsApi.createReference(clean) : await documentsApi.upload(file!, clean, setProgress);
      toast.success(referenceOnly ? "Document recorded" : "Document uploaded", "It needs review/approval before it counts as evidence.");
      qc.invalidateQueries({ queryKey: ["documents"] });
      qc.invalidateQueries({ queryKey: ["compliance"] });
      onClose();
      router.push(`/documents/${d.id}`);
    } catch (e) {
      const existing = e instanceof ApiRequestError ? (e.details as { existingDocumentId?: string } | undefined)?.existingDocumentId : undefined;
      if (existing) setDuplicate(existing);
      else toast.error("Upload failed", toFriendlyErrorMessage(e));
    } finally {
      setBusy(false);
    }
  };
  return (
    <Modal
      open={open}
      onOpenChange={(o) => !o && onClose()}
      title={defaults.replacesDocumentId ? "Upload replacement version" : "Upload external document"}
      description={defaults.requirementName ? `Evidence for: ${defaults.requirementName}` : "Official, carrier, bank or buyer documents. Stored privately. ExportPro records them; it does not verify authenticity."}
      className="max-h-[90vh] max-w-lg overflow-y-auto"
      footer={
        <>
          <Button variant="outline" onClick={onClose} disabled={busy}>Cancel</Button>
          <Button onClick={() => submit()} loading={busy} disabled={!referenceOnly && !file}>{referenceOnly ? "Record" : "Upload"}</Button>
        </>
      }
    >
      <div className="flex flex-col gap-3">
        <Select label="Document type" value={f.documentType} onChange={(e) => set("documentType", e.target.value)} options={types.map((t) => ({ value: t, label: DOC_TYPE[t] }))} disabled={Boolean(defaults.replacesDocumentId)} />
        <div className="grid gap-3 sm:grid-cols-2">
          <Select label="Source (who issued it)" value={f.source} onChange={(e) => set("source", e.target.value)} options={EXTERNAL_SOURCES.map((s) => ({ value: s, label: SOURCE[s].label }))} />
          <Select label="Provided by" value={f.responsibleParty} onChange={(e) => set("responsibleParty", e.target.value)} options={RESPONSIBLE_PARTIES.map((p) => ({ value: p, label: PARTY[p] }))} />
          <Input label="Document number" value={f.documentNumber} onChange={(e) => set("documentNumber", e.target.value)} maxLength={80} />
          <Input label="Issuer" value={f.issuer} onChange={(e) => set("issuer", e.target.value)} maxLength={160} />
          <Input label="Issue date" type="date" value={f.issueDate} onChange={(e) => set("issueDate", e.target.value)} />
          <Input label="Expiry date" type="date" value={f.expiryDate} onChange={(e) => set("expiryDate", e.target.value)} />
        </div>
        <Textarea label="Notes" rows={2} value={f.notes} onChange={(e) => set("notes", e.target.value)} maxLength={2000} />
        {!defaults.replacesDocumentId && <Checkbox label="Record by reference only (no file yet, e.g. a shipping bill number)" checked={referenceOnly} onChange={(e) => setReferenceOnly(e.target.checked)} />}
        {!referenceOnly && (
          <div>
            <label htmlFor="trade-doc-file" className="text-sm font-medium">File</label>
            <input id="trade-doc-file" type="file" accept={ACCEPT} className="mt-1 block w-full text-sm" onChange={(e) => { setFile(e.target.files?.[0] ?? null); setDuplicate(null); }} />
            <Caption>PDF, image, Word, Excel, CSV or text, up to 10 MB. Executables are rejected. Files are not malware-scanned.</Caption>
            {busy && <Progress value={progress} aria-label="Upload progress" className="mt-2" />}
          </div>
        )}
        {duplicate && (
          <div role="alert" className="rounded-md border border-warning/40 bg-warning/5 p-2 text-sm">
            This exact file is already stored. <a className="text-primary hover:underline" href={`/documents/${duplicate}`}>Open existing</a> or{" "}
            <button type="button" className="text-primary hover:underline" onClick={() => submit(true)}>upload anyway</button>.
          </div>
        )}
      </div>
    </Modal>
  );
}
