import { MembershipRole } from "./enums";

/**
 * Current permission namespace. Add to this union as real business
 * modules land — don't pre-populate `buyers.*`/`crm.*`/`shipments.*`
 * etc. before those modules exist, per ARCHITECTURE.md.
 */
export const PERMISSIONS = [
  "organization.view",
  "organization.update",
  "team.view",
  "team.invite",
  "team.update",
  "team.remove",
  "profile.view",
  "profile.update",
  "security.manage",
  "audit.view",
  "onboarding.view",
  "onboarding.update",
  "readiness.view",
  "documents.upload",
  "opportunities.view",
  "opportunities.save",
  "opportunities.manage_saved_searches",
  "products.view",
  "products.analyze",
  "products.create",
  "products.update",
  "products.confirm_classification",
  "product_intelligence.view",
  "country_intelligence.view",
  "comparisons.view",
  "recommendations.view",
  "trade_data.view",
  "trade_data.manage",
  "trade_data.ingest",
  "buyers.view",
  "buyers.save",
  "buyers.notes",
  "buyers.crm_handoff",
  "buyers.create",
  "crm.view",
  "crm.create",
  "crm.edit",
  "crm.stage_change",
  "crm.assign",
  "crm.notes",
  "crm.tasks",
  "crm.attachments",
  "crm.manage",
  "outreach.view",
  "outreach.create",
  "outreach.edit",
  "outreach.launch",
  "outreach.pause",
  "outreach.templates",
  "outreach.settings",
  "costing.view",
  "costing.create",
  "costing.edit",
  "costing.edit_logistics",
  "costing.calculate",
  "costing.ready",
  "costing.lock",
  "inquiries.view",
  "inquiries.create",
  "inquiries.edit",
  "inquiries.assign",
  "inquiries.qualify",
  "inquiries.approve",
  "inquiries.archive",
  "inquiries.create_handoff",
] as const;
export type Permission = (typeof PERMISSIONS)[number];

/**
 * Centralized role → permission mapping. This is the single source of
 * truth for authorization: the backend's PermissionGuard and the
 * frontend's permission helper both import this exact map, so there is
 * no way for the two layers to drift apart.
 *
 * A user can always view/update their OWN profile regardless of role —
 * that isn't a permission check, it's an identity check — so
 * `profile.*` here governs managing *other* users' profiles only
 * (nothing currently uses that distinction, but the permission exists
 * for when it does).
 */
export const ROLE_PERMISSIONS: Record<MembershipRole, readonly Permission[]> = {
  OWNER: [
    "organization.view",
    "organization.update",
    "team.view",
    "team.invite",
    "team.update",
    "team.remove",
    "profile.view",
    "profile.update",
    "security.manage",
    "audit.view",
    "onboarding.view",
    "onboarding.update",
    "readiness.view",
    "documents.upload",
    "opportunities.view",
    "opportunities.save",
    "opportunities.manage_saved_searches",
    "products.view",
    "product_intelligence.view",
    "country_intelligence.view",
    "comparisons.view",
    "recommendations.view",
    "products.analyze",
    "products.create",
    "products.update",
    "products.confirm_classification",
    "trade_data.view",
    "trade_data.manage",
    "trade_data.ingest",
    "buyers.view",
    "buyers.save",
    "buyers.notes",
    "buyers.crm_handoff",
    "buyers.create",
    "crm.view",
    "crm.create",
    "crm.edit",
    "crm.stage_change",
    "crm.assign",
    "crm.notes",
    "crm.tasks",
    "crm.attachments",
    "crm.manage",
    "outreach.view",
    "outreach.create",
    "outreach.edit",
    "outreach.launch",
    "outreach.pause",
    "outreach.templates",
    "outreach.settings",
    "costing.view",
    "costing.create",
    "costing.edit",
    "costing.edit_logistics",
    "costing.calculate",
    "costing.ready",
    "costing.lock",
    "inquiries.view",
    "inquiries.create",
    "inquiries.edit",
    "inquiries.assign",
    "inquiries.qualify",
    "inquiries.approve",
    "inquiries.archive",
    "inquiries.create_handoff",
  ],
  // Same as OWNER except owner-only destructive actions (transfer
  // ownership, delete organization) are enforced by explicit role
  // checks in the relevant services, not by a permission string.
  ADMIN: [
    "organization.view",
    "organization.update",
    "team.view",
    "team.invite",
    "team.update",
    "team.remove",
    "profile.view",
    "profile.update",
    "security.manage",
    "audit.view",
    "onboarding.view",
    "onboarding.update",
    "readiness.view",
    "documents.upload",
    "opportunities.view",
    "opportunities.save",
    "opportunities.manage_saved_searches",
    "products.view",
    "product_intelligence.view",
    "country_intelligence.view",
    "comparisons.view",
    "recommendations.view",
    "products.analyze",
    "products.create",
    "products.update",
    "products.confirm_classification",
    "trade_data.view",
    "trade_data.manage",
    "trade_data.ingest",
    "buyers.view",
    "buyers.save",
    "buyers.notes",
    "buyers.crm_handoff",
    "buyers.create",
    "crm.view",
    "crm.create",
    "crm.edit",
    "crm.stage_change",
    "crm.assign",
    "crm.notes",
    "crm.tasks",
    "crm.attachments",
    "crm.manage",
    "outreach.view",
    "outreach.create",
    "outreach.edit",
    "outreach.launch",
    "outreach.pause",
    "outreach.templates",
    "outreach.settings",
    "costing.view",
    "costing.create",
    "costing.edit",
    "costing.edit_logistics",
    "costing.calculate",
    "costing.ready",
    "costing.lock",
    "inquiries.view",
    "inquiries.create",
    "inquiries.edit",
    "inquiries.assign",
    "inquiries.qualify",
    "inquiries.approve",
    "inquiries.archive",
    "inquiries.create_handoff",
  ],
  // Can run the exporter-onboarding wizard and opportunity discovery day
  // to day, but not manage team membership or organization identity.
  EXPORT_MANAGER: [
    "organization.view",
    "team.view",
    "profile.view",
    "onboarding.view",
    "onboarding.update",
    "readiness.view",
    "documents.upload",
    "opportunities.view",
    "opportunities.save",
    "opportunities.manage_saved_searches",
    "products.view",
    "product_intelligence.view",
    "country_intelligence.view",
    "comparisons.view",
    "recommendations.view",
    "products.analyze",
    "products.create",
    "products.update",
    "products.confirm_classification",
    "trade_data.view",
    "buyers.view",
    "buyers.save",
    "buyers.notes",
    "buyers.crm_handoff",
    "buyers.create",
    "crm.view",
    "crm.create",
    "crm.edit",
    "crm.stage_change",
    "crm.assign",
    "crm.notes",
    "crm.tasks",
    "crm.attachments",
    "crm.manage",
    "outreach.view",
    "outreach.create",
    "outreach.edit",
    "outreach.launch",
    "outreach.pause",
    "outreach.templates",
    "outreach.settings",
    "costing.view",
    "costing.create",
    "costing.edit",
    "costing.edit_logistics",
    "costing.calculate",
    "costing.ready",
    "costing.lock",
    "inquiries.view",
    "inquiries.create",
    "inquiries.edit",
    "inquiries.assign",
    "inquiries.qualify",
    "inquiries.approve",
    "inquiries.archive",
    "inquiries.create_handoff",
  ],
  SALES: [
    "organization.view",
    "team.view",
    "profile.view",
    "onboarding.view",
    "readiness.view",
    "opportunities.view",
    "opportunities.save",
    "products.view",
    "product_intelligence.view",
    "country_intelligence.view",
    "comparisons.view",
    "recommendations.view",
    "products.analyze",
    "buyers.view",
    "buyers.save",
    "buyers.notes",
    "buyers.crm_handoff",
    "buyers.create",
    "crm.view",
    "crm.create",
    "crm.edit",
    "crm.stage_change",
    "crm.notes",
    "crm.tasks",
    "crm.attachments",
    "outreach.view",
    "outreach.create",
    "outreach.edit",
    "outreach.launch",
    "outreach.templates",
    "costing.view",
    "costing.create",
    "costing.edit",
    "costing.calculate",
    "inquiries.view",
    "inquiries.create",
    "inquiries.edit",
    "inquiries.assign",
    "inquiries.qualify",
    "inquiries.create_handoff",
  ],
  // Classification support: can run analyses, answer clarifications and
  // pre-select candidates, but confirming/saving stays with managers.
  DOCUMENTATION: [
    "organization.view",
    "team.view",
    "profile.view",
    "onboarding.view",
    "readiness.view",
    "opportunities.view",
    "products.view",
    "product_intelligence.view",
    "country_intelligence.view",
    "comparisons.view",
    "recommendations.view",
    "products.analyze",
    "trade_data.view",
    "buyers.view",
    "crm.view",
    "crm.notes",
    "crm.attachments",
    "outreach.view",
    "costing.view",
    "inquiries.view",
    "inquiries.edit",
  ],
  LOGISTICS: ["organization.view", "team.view", "profile.view", "onboarding.view", "readiness.view", "opportunities.view", "products.view", "product_intelligence.view", "country_intelligence.view", "comparisons.view", "recommendations.view", "buyers.view", "crm.view", "outreach.view", "costing.view", "costing.edit_logistics", "costing.calculate", "inquiries.view"],
  FINANCE: ["organization.view", "team.view", "profile.view", "onboarding.view", "readiness.view", "opportunities.view", "products.view", "product_intelligence.view", "country_intelligence.view", "comparisons.view", "recommendations.view", "buyers.view", "crm.view", "outreach.view", "costing.view", "costing.create", "costing.edit", "costing.calculate", "costing.ready", "inquiries.view"],
  VIEWER: ["organization.view", "profile.view", "onboarding.view", "readiness.view", "opportunities.view", "products.view", "product_intelligence.view", "country_intelligence.view", "comparisons.view", "recommendations.view", "buyers.view", "crm.view", "outreach.view", "costing.view", "inquiries.view"],
};

export function roleHasPermission(role: MembershipRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}

export function permissionsForRole(role: MembershipRole): Permission[] {
  return [...ROLE_PERMISSIONS[role]];
}
