/** State/UT code → name and broad region, used to derive regional totals from state-level data only. */
export const INDIAN_STATES: Record<string, { name: string; region: string }> = {
  AP: { name: 'Andhra Pradesh', region: 'Southern India' },
  AS: { name: 'Assam', region: 'North-Eastern India' },
  BR: { name: 'Bihar', region: 'Eastern India' },
  CG: { name: 'Chhattisgarh', region: 'Central India' },
  DL: { name: 'Delhi', region: 'Northern India' },
  GA: { name: 'Goa', region: 'Western India' },
  GJ: { name: 'Gujarat', region: 'Western India' },
  HP: { name: 'Himachal Pradesh', region: 'Northern India' },
  HR: { name: 'Haryana', region: 'Northern India' },
  JH: { name: 'Jharkhand', region: 'Eastern India' },
  JK: { name: 'Jammu and Kashmir', region: 'Northern India' },
  KA: { name: 'Karnataka', region: 'Southern India' },
  KL: { name: 'Kerala', region: 'Southern India' },
  MH: { name: 'Maharashtra', region: 'Western India' },
  MP: { name: 'Madhya Pradesh', region: 'Central India' },
  OD: { name: 'Odisha', region: 'Eastern India' },
  PB: { name: 'Punjab', region: 'Northern India' },
  RJ: { name: 'Rajasthan', region: 'Northern India' },
  TN: { name: 'Tamil Nadu', region: 'Southern India' },
  TS: { name: 'Telangana', region: 'Southern India' },
  UK: { name: 'Uttarakhand', region: 'Northern India' },
  UP: { name: 'Uttar Pradesh', region: 'Northern India' },
  WB: { name: 'West Bengal', region: 'Eastern India' },
  AR: { name: 'Arunachal Pradesh', region: 'North-Eastern India' },
  MN: { name: 'Manipur', region: 'North-Eastern India' },
  ML: { name: 'Meghalaya', region: 'North-Eastern India' },
  MZ: { name: 'Mizoram', region: 'North-Eastern India' },
  NL: { name: 'Nagaland', region: 'North-Eastern India' },
  SK: { name: 'Sikkim', region: 'North-Eastern India' },
  TR: { name: 'Tripura', region: 'North-Eastern India' },
  PY: { name: 'Puducherry', region: 'Southern India' },
  CH: { name: 'Chandigarh', region: 'Northern India' },
  LA: { name: 'Ladakh', region: 'Northern India' },
  AN: { name: 'Andaman and Nicobar Islands', region: 'Southern India' },
  LD: { name: 'Lakshadweep', region: 'Southern India' },
  DH: {
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    region: 'Western India',
  },
};
