import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Inject,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Prisma } from '@prisma/client';
import {
  DOCUMENT_EXTRACTION_SCHEMA_VERSION,
  EXTRACTION_HEADER_FIELDS,
  EXTRACTION_ITEM_FIELDS,
  roleHasPermission,
  TRADE_DOCUMENT_TYPES,
  type ConfirmedDocumentData,
  type DocumentExtractionOverview,
  type DocumentExtractionStatus,
  type DocumentExtractionView,
  type ExtractionProvenance,
  type ExtractionResult,
  type MembershipRole,
  type TextAvailability,
  type TradeDocumentType,
} from '@exportpro/types';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import {
  CommercialCoreService,
  type Actor,
  iso,
} from '../commercial/commercial-core.service';
import { StorageService } from '../storage/storage.service';
import {
  ConfirmExtractionDto,
  ExtractDto,
  ManualExtractionDto,
} from './document-validation.dto';
import {
  groundExtraction,
  missingFields,
  normalizeField,
} from './extraction/grounding';
import {
  DOCUMENT_EXTRACTION_PROVIDER,
  type DocumentExtractionProvider,
  ExtractionProviderError,
} from './extraction/providers';
import { usesDecimalComma } from './normalize';
import { extractPdfText } from './pdf-text';
import { DocumentValidationService } from './validation.service';

type Doc = Prisma.TradeDocumentGetPayload<object>;
type Extraction = Prisma.DocumentExtractionGetPayload<object>;

const LOGISTICS_TYPES = [
  'PACKING_LIST',
  'SHIPPING_INSTRUCTION',
  'BILL_OF_LADING',
  'AIRWAY_BILL',
  'SHIPPING_BILL',
  'OTHER_SHIPPING_DOCUMENT',
];
const FINANCE_TYPES = [
  'COMMERCIAL_INVOICE',
  'PROFORMA_INVOICE',
  'PURCHASE_ORDER',
  'INSURANCE_CERTIFICATE',
];

/** Logistics reviewers handle logistics documents, finance reviewers commercial ones; others per permission. */
export function canReviewType(role: MembershipRole, type: string) {
  if (!roleHasPermission(role, 'document_validation.review')) return false;
  if (role === 'LOGISTICS') return LOGISTICS_TYPES.includes(type);
  if (role === 'FINANCE') return FINANCE_TYPES.includes(type);
  return true;
}

const fileKind = (
  mime: string | null,
): DocumentExtractionOverview['fileKind'] =>
  !mime
    ? 'NONE'
    : mime === 'application/pdf'
      ? 'PDF'
      : mime.startsWith('image/')
        ? 'IMAGE'
        : mime.startsWith('text/')
          ? 'TEXT'
          : 'OFFICE';

@Injectable()
export class DocumentExtractionService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
    private readonly storage: StorageService,
    private readonly core: CommercialCoreService,
    private readonly validation: DocumentValidationService,
    @Inject(DOCUMENT_EXTRACTION_PROVIDER)
    private readonly provider: DocumentExtractionProvider,
  ) {}

  private async doc(a: Actor, id: string): Promise<Doc> {
    if (!roleHasPermission(a.role, 'documents.view'))
      throw new NotFoundException('Document not found.');
    const d = await this.prisma.tradeDocument.findFirst({
      where: { id, organizationId: a.organizationId },
    });
    if (!d) throw new NotFoundException('Document not found.');
    return d;
  }

  private cacheKey(d: Doc) {
    const p = this.provider.identity;
    return `${d.id}:v${d.version}:${p.name}:${p.model ?? '-'}:${DOCUMENT_EXTRACTION_SCHEMA_VERSION}:${p.promptVersion ?? '-'}`;
  }

  private unavailableReason(d: Doc): string | null {
    if (d.generated)
      return 'Generated by ExportPro — its stored structured data is used directly (no extraction needed).';
    if (!d.storageKey) return 'No file attached — enter the data manually.';
    const k = fileKind(d.mimeType);
    if (this.provider.identity.type === 'NONE')
      return 'Automated extraction is not configured — enter the data manually.';
    if (k === 'OFFICE')
      return 'Text extraction is not available for Word/Excel files — enter the data manually.';
    if (k === 'IMAGE' && !this.provider.identity.acceptsFiles)
      return 'Text extraction not available for images (OCR is not configured) — enter the data manually.';
    return null;
  }

  /** Reads the text layer where the infrastructure reliably can; never pretends OCR happened. */
  private async text(d: Doc): Promise<{
    text: string | null;
    file: Buffer | null;
    availability: TextAvailability;
  }> {
    const buf = await this.storage
      .readPrivateFile(d.storageKey!)
      .catch(() => null);
    if (!buf) return { text: null, file: null, availability: 'UNAVAILABLE' };
    const k = fileKind(d.mimeType);
    if (k === 'TEXT')
      return { text: buf.toString('utf8'), file: null, availability: 'TEXT' };
    if (k === 'PDF') {
      const t = extractPdfText(buf);
      if (t.length >= 20)
        return { text: t, file: null, availability: 'PDF_TEXT_LAYER' };
      return this.provider.identity.acceptsFiles
        ? { text: null, file: buf, availability: 'AI_FILE_INPUT' }
        : { text: null, file: null, availability: 'UNAVAILABLE' };
    }
    if (k === 'IMAGE' && this.provider.identity.acceptsFiles)
      return { text: null, file: buf, availability: 'AI_FILE_INPUT' };
    return { text: null, file: null, availability: 'UNAVAILABLE' };
  }

  async extract(a: Actor, id: string, dto: ExtractDto) {
    const d = await this.doc(a, id);
    if (d.generated)
      throw new ConflictException({
        message:
          'This document was generated by ExportPro; its stored structured data is authoritative and is used for validation without extraction.',
        details: { code: 'STRUCTURED_SOURCE' },
      });
    if (!d.storageKey)
      throw new BadRequestException({
        message: 'No file attached — use manual entry.',
        details: { code: 'NO_FILE' },
      });
    const key = this.cacheKey(d);
    // Idempotent: same document version + provider + schema/prompt reuses the existing result unless forced.
    const existing = await this.prisma.documentExtraction.findFirst({
      where: {
        organizationId: a.organizationId,
        cacheKey: key,
        status: { notIn: ['FAILED'] },
      },
      orderBy: { extractionVersion: 'desc' },
    });
    if (existing && !dto.force) return this.overview(a, id);
    const version =
      ((
        await this.prisma.documentExtraction.aggregate({
          where: { tradeDocumentId: d.id },
          _max: { extractionVersion: true },
        })
      )._max.extractionVersion ?? 0) + 1;
    const p = this.provider.identity;
    const row = await this.prisma.documentExtraction.create({
      data: {
        organizationId: a.organizationId,
        tradeDocumentId: d.id,
        documentVersion: d.version,
        extractionVersion: version,
        cacheKey: key,
        providerType:
          p.type === 'AI' ? 'AI' : p.type === 'RULE' ? 'RULE' : 'AI',
        providerName: p.name,
        providerModel: p.model,
        promptVersion: p.promptVersion,
        schemaVersion: DOCUMENT_EXTRACTION_SCHEMA_VERSION,
        status: 'PROCESSING',
        textAvailability: 'UNAVAILABLE',
        createdByUserId: a.userId,
      },
    });
    await this.audit.record({
      organizationId: a.organizationId,
      actorId: a.userId,
      action: 'document.extraction_started',
      entityType: 'TradeDocument',
      entityId: d.id,
      metadata: {
        extractionVersion: version,
        provider: p.name,
        documentVersion: d.version,
      },
    });
    const unavailable = this.unavailableReason(d);
    const src = unavailable
      ? {
          text: null,
          file: null,
          availability: 'UNAVAILABLE' as TextAvailability,
        }
      : await this.text(d);
    let status: DocumentExtractionStatus = 'FAILED';
    let result: ExtractionResult | null = null;
    let error: string | null = null;
    let raw: unknown = null;
    let overall: number | null = null;
    const warnings: string[] = [];
    if (unavailable || src.availability === 'UNAVAILABLE') {
      error =
        unavailable ??
        'Text extraction not available (scanned or image-only file; OCR is not configured). Enter the data manually.';
    } else {
      try {
        const out = await this.provider.extract({
          declaredType: d.documentType,
          filename: d.originalFilename ?? 'document',
          mimeType: d.mimeType ?? '',
          text: src.text,
          file: src.file,
        });
        raw = out;
        const g = groundExtraction(
          out,
          src.text,
          p.type === 'AI' ? 'AI_EXTRACTED' : 'RULE_EXTRACTED',
          src.text ? usesDecimalComma(src.text) : false,
        );
        result = g.result;
        overall =
          typeof out.overallConfidence === 'number'
            ? Math.max(0, Math.min(100, Math.round(out.overallConfidence)))
            : null;
        const anyAmbiguous =
          Object.values(result.fields).some((f) => f?.ambiguous) ||
          result.items.some((i) =>
            Object.values(i.fields).some((f) => f?.ambiguous),
          ) ||
          result.ambiguities.length > 0;
        status =
          !Object.keys(result.fields).length && !result.items.length
            ? 'FAILED'
            : anyAmbiguous
              ? 'NEEDS_REVIEW'
              : g.fieldProblems
                ? 'PARTIAL'
                : 'COMPLETED';
        if (status === 'FAILED')
          error =
            'No labelled values could be read from this document. Enter the data manually.';
        if (
          result.detectedType.value &&
          result.detectedType.value !== d.documentType
        )
          warnings.push(
            `Looks like ${result.detectedType.value.replace(/_/g, ' ').toLowerCase()} (selected: ${d.documentType.replace(/_/g, ' ').toLowerCase()}). Confirm the type when reviewing.`,
          );
      } catch (e) {
        error =
          e instanceof ExtractionProviderError
            ? e.message
            : 'Extraction failed.';
      }
    }
    await this.prisma.documentExtraction.update({
      where: { id: row.id },
      data: {
        status,
        textAvailability: src.availability,
        detectedDocumentType: result?.detectedType.value ?? null,
        documentTypeConfidence: result?.detectedType.confidence ?? null,
        result: (result ?? undefined) as unknown as
          Prisma.InputJsonValue | undefined,
        rawStructuredOutput: (raw ?? undefined) as
          Prisma.InputJsonValue | undefined,
        overallConfidence: overall,
        warnings: warnings as Prisma.InputJsonValue,
        errorMessage: error,
        completedAt: new Date(),
      },
    });
    await this.core.event(this.prisma, a, {
      entityType: 'DOCUMENT',
      entityId: d.id,
      lineageId: d.rootId,
      type: status === 'FAILED' ? 'EXTRACTION_FAILED' : 'EXTRACTED',
      title:
        status === 'FAILED'
          ? `Extraction v${version} failed: ${error}`
          : `Extraction v${version} completed (${p.type === 'AI' ? 'AI' : 'rule-based'}) — needs human review`,
    });
    await this.audit.record({
      organizationId: a.organizationId,
      actorId: a.userId,
      action: 'document.extraction_completed',
      entityType: 'TradeDocument',
      entityId: d.id,
      metadata: {
        extractionVersion: version,
        status,
        fields: result ? Object.keys(result.fields).length : 0,
        items: result?.items.length ?? 0,
      },
    });
    return this.overview(a, id);
  }

  // ------------------------------------------------------------- review

  private buildConfirmed(
    base: ExtractionResult | null,
    dto: ConfirmExtractionDto | ManualExtractionDto,
    decimalComma: boolean,
  ) {
    const unknown = new Set(dto.unknownFields ?? []);
    let corrections = 0;
    const fields: ConfirmedDocumentData['fields'] = {};
    const problems: string[] = [];
    const header = new Set<string>(EXTRACTION_HEADER_FIELDS);
    const itemNames = new Set<string>(EXTRACTION_ITEM_FIELDS);
    if (base) {
      const missing = Object.keys(base.fields).filter(
        (k) => !(k in (dto.fields ?? {})) && !unknown.has(k),
      );
      if (missing.length)
        problems.push(
          `Review every extracted field (missing: ${missing.join(', ')}).`,
        );
    }
    for (const [name, rawValue] of Object.entries(dto.fields ?? {})) {
      if (!header.has(name)) {
        problems.push(`Unknown field ${name}.`);
        continue;
      }
      const raw = unknown.has(name)
        ? null
        : rawValue === null || rawValue === undefined
          ? null
          : String(rawValue).trim() || null;
      const n = normalizeField(name, raw, decimalComma);
      if (raw && (n.ambiguous || n.value === null))
        problems.push(`${name}: ${n.note ?? 'invalid value'}`);
      const extracted = base?.fields[name as keyof ExtractionResult['fields']];
      let provenance: ExtractionProvenance = 'USER_ENTERED';
      if (extracted) {
        if (
          (extracted.value ?? null) === (n.value ?? null) &&
          !extracted.ambiguous
        )
          provenance = 'USER_CONFIRMED';
        else {
          provenance = 'USER_CORRECTED';
          corrections++;
        }
      } else if (raw) corrections++;
      if (raw || extracted || unknown.has(name))
        fields[name as keyof typeof fields] = {
          value: n.value,
          raw,
          provenance,
          unknown: unknown.has(name),
        };
    }
    for (const u of unknown)
      if (!fields[u as keyof typeof fields] && header.has(u))
        fields[u as keyof typeof fields] = {
          value: null,
          raw: null,
          provenance: 'USER_ENTERED',
          unknown: true,
        };
    const items: ConfirmedDocumentData['items'] = (dto.items ?? []).map(
      (it, idx) => {
        const out: ConfirmedDocumentData['items'][number]['fields'] = {};
        const prev = base?.items[idx]?.fields;
        for (const [name, rawValue] of Object.entries(it ?? {})) {
          if (!itemNames.has(name)) continue;
          const raw =
            rawValue === null || rawValue === undefined
              ? null
              : String(rawValue).trim() || null;
          const n = normalizeField(name, raw, decimalComma);
          if (raw && (n.ambiguous || n.value === null))
            problems.push(
              `Item ${idx + 1} ${name}: ${n.note ?? 'invalid value'}`,
            );
          const e = prev?.[name as keyof typeof prev];
          let provenance: ExtractionProvenance = 'USER_ENTERED';
          if (e) {
            if ((e.value ?? null) === (n.value ?? null) && !e.ambiguous)
              provenance = 'USER_CONFIRMED';
            else {
              provenance = 'USER_CORRECTED';
              corrections++;
            }
          } else if (raw) corrections++;
          if (raw || e)
            out[name as keyof typeof out] = { value: n.value, raw, provenance };
        }
        return { fields: out };
      },
    );
    if (base && items.length !== base.items.length)
      corrections += Math.abs(items.length - base.items.length);
    items.forEach((it, i) => {
      if (!it.fields.description?.value)
        problems.push(`Item ${i + 1}: description is required.`);
    });
    return { fields, items, corrections, problems };
  }

  async confirm(
    a: Actor,
    id: string,
    extractionId: string,
    dto: ConfirmExtractionDto,
  ) {
    const d = await this.doc(a, id);
    if (!canReviewType(a.role, d.documentType))
      throw new ForbiddenException('You cannot review this type of document.');
    const ex = await this.prisma.documentExtraction.findFirst({
      where: {
        id: extractionId,
        tradeDocumentId: d.id,
        organizationId: a.organizationId,
      },
    });
    if (!ex) throw new NotFoundException('Extraction not found.');
    if (ex.status === 'FAILED' || ex.status === 'PROCESSING' || !ex.result)
      throw new ConflictException(
        'This extraction has no result to confirm — run it again or enter the data manually.',
      );
    if (ex.documentVersion !== d.version)
      throw new ConflictException(
        'This extraction was made for an older document version. Extract the current version.',
      );
    const result = ex.result as unknown as ExtractionResult;
    return this.storeConfirmed(a, d, ex, result, dto);
  }

  async manual(a: Actor, id: string, dto: ManualExtractionDto) {
    const d = await this.doc(a, id);
    if (d.generated)
      throw new ConflictException({
        message:
          'Generated documents already have authoritative structured data.',
        details: { code: 'STRUCTURED_SOURCE' },
      });
    if (!canReviewType(a.role, d.documentType))
      throw new ForbiddenException('You cannot review this type of document.');
    const version =
      ((
        await this.prisma.documentExtraction.aggregate({
          where: { tradeDocumentId: d.id },
          _max: { extractionVersion: true },
        })
      )._max.extractionVersion ?? 0) + 1;
    const ex = await this.prisma.documentExtraction.create({
      data: {
        organizationId: a.organizationId,
        tradeDocumentId: d.id,
        documentVersion: d.version,
        extractionVersion: version,
        cacheKey: `${d.id}:v${d.version}:manual:${version}`,
        providerType: 'MANUAL',
        providerName: 'manual-entry',
        schemaVersion: DOCUMENT_EXTRACTION_SCHEMA_VERSION,
        status: 'CONFIRMED',
        textAvailability: 'UNAVAILABLE',
        completedAt: new Date(),
        createdByUserId: a.userId,
      },
    });
    return this.storeConfirmed(a, d, ex, null, dto);
  }

  private async storeConfirmed(
    a: Actor,
    d: Doc,
    ex: Extraction,
    base: ExtractionResult | null,
    dto: ConfirmExtractionDto | ManualExtractionDto,
  ) {
    const type = (dto.confirmedDocumentType ??
      d.documentType) as TradeDocumentType;
    if (!(TRADE_DOCUMENT_TYPES as readonly string[]).includes(type))
      throw new BadRequestException('Unknown document type.');
    if (
      ['COMMERCIAL_INVOICE', 'PACKING_LIST', 'SHIPPING_INSTRUCTION'].includes(
        type,
      ) &&
      type !== d.documentType
    )
      throw new BadRequestException(
        'Uploaded documents cannot be reclassified as ExportPro-generated document types.',
      );
    if (type !== d.documentType && !dto.confirmTypeChange)
      throw new BadRequestException({
        message: `The confirmed type (${type}) differs from the document’s type (${d.documentType}). Confirm the type change explicitly.`,
        details: { code: 'TYPE_CONFIRMATION_REQUIRED' },
      });
    const b = this.buildConfirmed(base, dto, false);
    if (b.problems.length)
      throw new BadRequestException({
        message: 'Fix the reviewed values before confirming.',
        details: { code: 'VALIDATION', problems: b.problems },
      });
    const row = await this.prisma.$transaction(async (tx) => {
      const c = await tx.documentConfirmedData.create({
        data: {
          organizationId: a.organizationId,
          tradeDocumentId: d.id,
          documentVersion: d.version,
          extractionId: ex.id,
          confirmedDocumentType: type,
          data: {
            fields: b.fields,
            items: b.items,
          } as unknown as Prisma.InputJsonValue,
          correctionCount: b.corrections,
          note: dto.note?.trim() || null,
          reviewedByUserId: a.userId,
        },
      });
      // Extraction status is metadata only; its stored result is never edited.
      if (ex.providerType !== 'MANUAL')
        await tx.documentExtraction.update({
          where: { id: ex.id },
          data: { status: 'CONFIRMED' },
        });
      // A type change is applied to the document only while it is still editable.
      if (
        type !== d.documentType &&
        ['UPLOADED', 'REJECTED'].includes(d.status)
      )
        await tx.tradeDocument.update({
          where: { id: d.id },
          data: { documentType: type },
        });
      await this.core.event(tx, a, {
        entityType: 'DOCUMENT',
        entityId: d.id,
        lineageId: d.rootId,
        type: 'EXTRACTION_REVIEWED',
        title: `${ex.providerType === 'MANUAL' ? 'Data entered manually' : `Extraction v${ex.extractionVersion} reviewed`} (${b.corrections} correction${b.corrections === 1 ? '' : 's'})`,
      });
      return c;
    });
    await this.audit.record({
      organizationId: a.organizationId,
      actorId: a.userId,
      action: 'document.extraction_reviewed',
      entityType: 'TradeDocument',
      entityId: d.id,
      metadata: {
        confirmedId: row.id,
        extractionVersion: ex.extractionVersion,
        corrections: b.corrections,
        manual: ex.providerType === 'MANUAL',
        typeChanged: type !== d.documentType,
      },
    });
    // Deterministic validation may run automatically after confirmation; sign-off stays human.
    if (d.purchaseOrderId)
      await this.validation.runForDocument(a, d.id, true).catch(() => null);
    return this.overview(a, d.id);
  }

  // -------------------------------------------------------------- reads

  private view(
    x: Extraction,
    names: Map<string, string>,
  ): DocumentExtractionView {
    const result = (x.result ?? null) as unknown as ExtractionResult | null;
    return {
      id: x.id,
      tradeDocumentId: x.tradeDocumentId,
      documentVersion: x.documentVersion,
      extractionVersion: x.extractionVersion,
      providerType: x.providerType as DocumentExtractionView['providerType'],
      providerName: x.providerName,
      providerModel: x.providerModel,
      promptVersion: x.promptVersion,
      schemaVersion: x.schemaVersion,
      status: x.status as DocumentExtractionStatus,
      textAvailability: x.textAvailability as TextAvailability,
      detectedDocumentType: x.detectedDocumentType as TradeDocumentType | null,
      documentTypeConfidence:
        x.documentTypeConfidence as DocumentExtractionView['documentTypeConfidence'],
      overallConfidence: x.overallConfidence,
      result,
      warnings: (x.warnings as string[]) ?? [],
      errorMessage: x.errorMessage,
      missingFields: missingFields(result, x.detectedDocumentType ?? ''),
      startedAt: x.startedAt.toISOString(),
      completedAt: iso(x.completedAt),
      createdBy: x.createdByUserId
        ? (names.get(x.createdByUserId) ?? null)
        : null,
    };
  }

  async overview(a: Actor, id: string): Promise<DocumentExtractionOverview> {
    const d = await this.doc(a, id);
    if (!roleHasPermission(a.role, 'document_validation.view'))
      throw new ForbiddenException('No access to document validation.');
    const [rows, confirmed] = await Promise.all([
      this.prisma.documentExtraction.findMany({
        where: { tradeDocumentId: d.id, organizationId: a.organizationId },
        orderBy: { extractionVersion: 'desc' },
      }),
      this.prisma.documentConfirmedData.findFirst({
        where: {
          tradeDocumentId: d.id,
          organizationId: a.organizationId,
          documentVersion: d.version,
        },
        orderBy: { reviewedAt: 'desc' },
        include: { extraction: { select: { extractionVersion: true } } },
      }),
    ]);
    const names = await this.core.userNames([
      ...rows.map((r) => r.createdByUserId),
      confirmed?.reviewedByUserId,
    ]);
    const reason = this.unavailableReason(d);
    const actions: string[] = [];
    const can = (p: Parameters<typeof roleHasPermission>[1]) =>
      roleHasPermission(a.role, p);
    if (!d.generated) {
      if (can('document_validation.extract') && !reason)
        actions.push('extract');
      if (canReviewType(a.role, d.documentType))
        actions.push('review', 'manual');
    }
    if (can('document_validation.extract') || can('document_validation.review'))
      actions.push('validate');
    const cd = confirmed?.data as unknown as
      | {
          fields: ConfirmedDocumentData['fields'];
          items: ConfirmedDocumentData['items'];
        }
      | undefined;
    return {
      documentId: d.id,
      documentType: d.documentType as TradeDocumentType,
      documentVersion: d.version,
      structured: d.generated,
      structuredData: d.generated
        ? await this.validation.viewForDocument(a.organizationId, d)
        : null,
      hasFile: Boolean(d.storageKey),
      fileKind: fileKind(d.mimeType),
      extractionAvailable: !reason,
      extractionUnavailableReason: reason,
      providerName: this.provider.identity.name,
      extractions: rows.map((r) => this.view(r, names)),
      confirmed: confirmed
        ? {
            id: confirmed.id,
            extractionId: confirmed.extractionId,
            extractionVersion: confirmed.extraction?.extractionVersion ?? null,
            documentVersion: confirmed.documentVersion,
            confirmedDocumentType:
              confirmed.confirmedDocumentType as TradeDocumentType,
            fields: cd?.fields ?? {},
            items: cd?.items ?? [],
            correctionCount: confirmed.correctionCount,
            note: confirmed.note,
            reviewedBy: names.get(confirmed.reviewedByUserId) ?? null,
            reviewedAt: confirmed.reviewedAt.toISOString(),
          }
        : null,
      availableActions: actions,
    };
  }

  async one(a: Actor, id: string, extractionId: string) {
    const d = await this.doc(a, id);
    const x = await this.prisma.documentExtraction.findFirst({
      where: {
        id: extractionId,
        tradeDocumentId: d.id,
        organizationId: a.organizationId,
      },
    });
    if (!x) throw new NotFoundException('Extraction not found.');
    return this.view(x, await this.core.userNames([x.createdByUserId]));
  }
}
