import type { Applicability, ComplianceReadiness, ComplianceSeverity, CoverageLevel, DocumentAvailability, DocumentSource, DocumentStatus, ExpiryState, RequirementBasis, RequirementLevel, RequirementStatus, ResponsibleParty, TradeDocumentType } from "@exportpro/types";

type Variant = "neutral" | "success" | "warning" | "danger" | "info";
const L = (label: string, variant: Variant) => ({ label, variant });

export const READINESS: Record<ComplianceReadiness, { label: string; variant: Variant }> = {
  NOT_READY: L("Not ready", "neutral"),
  BLOCKED: L("Blocked", "danger"),
  READY_WITH_WARNINGS: L("Ready with warnings", "warning"),
  READY: L("Ready", "success"),
};
export const REQ_STATUS: Record<RequirementStatus, { label: string; variant: Variant }> = {
  NOT_STARTED: L("Not started", "neutral"),
  MISSING: L("Missing", "danger"),
  IN_PROGRESS: L("In progress", "info"),
  DOCUMENT_UPLOADED: L("Uploaded — awaiting review", "info"),
  UNDER_REVIEW: L("Under review", "info"),
  SATISFIED: L("Satisfied", "success"),
  NOT_APPLICABLE: L("Not applicable", "neutral"),
  EXPIRED: L("Expired", "danger"),
  REJECTED: L("Rejected", "danger"),
  WAIVED: L("Waived", "warning"),
  ACCEPTED_RISK: L("Accepted risk", "warning"),
};
export const LEVEL: Record<RequirementLevel, { label: string; variant: Variant }> = {
  REQUIRED: L("Required", "danger"),
  CONDITIONAL: L("Conditional", "warning"),
  RECOMMENDED: L("Recommended", "info"),
  INFORMATIONAL: L("Informational", "neutral"),
};
export const SEVERITY: Record<ComplianceSeverity, { label: string; variant: Variant }> = {
  BLOCKER: L("Blocker", "danger"),
  WARNING: L("Warning", "warning"),
  INFO: L("Info", "neutral"),
};
export const BASIS: Record<RequirementBasis, string> = {
  REGULATORY_REQUIRED: "Regulatory",
  ADVISORY: "Advisory",
  BUYER_REQUESTED: "Buyer requested",
  USER_DEFINED: "User defined",
};
export const APPLICABILITY: Record<Applicability, string> = { APPLICABLE: "Applies", NOT_APPLICABLE: "Not applicable", UNKNOWN: "Unknown — needs confirmation" };
export const COVERAGE: Record<CoverageLevel, { label: string; variant: Variant }> = {
  COMPLETE: L("Complete (curated rules)", "success"),
  PARTIAL: L("Partial", "warning"),
  UNKNOWN: L("Unknown — coverage incomplete", "danger"),
};
export const DOC_TYPE: Record<TradeDocumentType, string> = {
  COMMERCIAL_INVOICE: "Commercial invoice",
  PACKING_LIST: "Packing list",
  SHIPPING_INSTRUCTION: "Shipping instruction",
  CERTIFICATE_OF_ORIGIN: "Certificate of origin",
  PHYTOSANITARY_CERTIFICATE: "Phytosanitary certificate",
  INSPECTION_CERTIFICATE: "Inspection certificate",
  TEST_CERTIFICATE: "Test / analysis certificate",
  FUMIGATION_CERTIFICATE: "Fumigation certificate",
  INSURANCE_CERTIFICATE: "Insurance certificate",
  SHIPPING_BILL: "Shipping bill",
  BILL_OF_LADING: "Bill of lading",
  AIRWAY_BILL: "Airway bill",
  REGISTRATION_CERTIFICATE: "Registration certificate",
  OTHER: "Other",
};
export const DOC_STATUS: Record<DocumentStatus, { label: string; variant: Variant }> = {
  DRAFT: L("Draft", "neutral"),
  GENERATED: L("Generated", "neutral"),
  UPLOADED: L("Uploaded", "info"),
  UNDER_REVIEW: L("Under review", "info"),
  APPROVED: L("Approved", "success"),
  REJECTED: L("Rejected", "danger"),
  ISSUED_EXTERNAL: L("Issued externally", "success"),
  EXPIRED: L("Expired", "danger"),
  SUPERSEDED: L("Superseded", "neutral"),
  ARCHIVED: L("Archived", "neutral"),
};
/** Generated vs uploaded vs external badge text. */
export const SOURCE: Record<DocumentSource, { label: string; variant: Variant }> = {
  SYSTEM_GENERATED: L("Generated by ExportPro", "info"),
  USER_UPLOADED: L("User uploaded", "neutral"),
  GOVERNMENT_ISSUED: L("External / Government", "warning"),
  CARRIER_ISSUED: L("Carrier issued", "warning"),
  INSPECTION_AGENCY: L("Inspection agency", "warning"),
  BANK: L("Bank", "warning"),
  BUYER: L("From buyer", "neutral"),
  OTHER: L("External / other", "neutral"),
};
export const PARTY: Record<ResponsibleParty, string> = {
  EXPORTER: "Exporter (you)",
  BUYER: "Buyer",
  GOVERNMENT: "Government / authority",
  CARRIER: "Carrier",
  BANK: "Bank",
  INSPECTION_AGENCY: "Inspection agency",
  CUSTOMS_BROKER: "Customs broker",
  OTHER: "Other",
};
export const AVAILABILITY: Record<DocumentAvailability, { label: string; variant: Variant }> = {
  NOT_AVAILABLE: L("Not available", "danger"),
  REQUESTED: L("Requested", "info"),
  DRAFT: L("Draft", "neutral"),
  AVAILABLE: L("Available — awaiting approval", "info"),
  APPROVED: L("Approved", "success"),
  EXPIRED: L("Expired", "danger"),
};
export const EXPIRY: Record<NonNullable<ExpiryState>, { label: string; variant: Variant }> = {
  VALID: L("Valid", "success"),
  EXPIRING_SOON: L("Expires soon", "warning"),
  EXPIRED: L("Expired", "danger"),
};
