import type { DocumentExtractionStatus, DocumentValidationStatus, ExtractionConfidence, ExtractionProvenance, MissingDocumentState, ValidationFindingStatus, ValidationSeverity } from "@exportpro/types";
import type { Applicability, ComplianceReadiness, ComplianceSeverity, CoverageLevel, DocumentAvailability, DocumentSource, DocumentStatus, ExpiryState, RequirementBasis, RequirementLevel, RequirementStatus, ResponsibleParty, TradeDocumentType } from "@exportpro/types";

type Variant = "neutral" | "success" | "warning" | "danger" | "info";
const L = (label: string, variant: Variant) => ({ label, variant });

export const READINESS: Record<ComplianceReadiness, { label: string; variant: Variant }> = {
  NOT_READY: L("Not ready", "neutral"),
  BLOCKED: L("Blocked", "danger"),
  READY_WITH_WARNINGS: L("Ready with warnings", "warning"),
  READY: L("Ready", "success"),
};
export const REQ_STATUS: Record<RequirementStatus, { label: string; variant: Variant }> = {
  NOT_STARTED: L("Not started", "neutral"),
  MISSING: L("Missing", "danger"),
  IN_PROGRESS: L("In progress", "info"),
  DOCUMENT_UPLOADED: L("Uploaded — awaiting review", "info"),
  UNDER_REVIEW: L("Under review", "info"),
  SATISFIED: L("Satisfied", "success"),
  NOT_APPLICABLE: L("Not applicable", "neutral"),
  EXPIRED: L("Expired", "danger"),
  REJECTED: L("Rejected", "danger"),
  WAIVED: L("Waived", "warning"),
  ACCEPTED_RISK: L("Accepted risk", "warning"),
};
export const LEVEL: Record<RequirementLevel, { label: string; variant: Variant }> = {
  REQUIRED: L("Required", "danger"),
  CONDITIONAL: L("Conditional", "warning"),
  RECOMMENDED: L("Recommended", "info"),
  INFORMATIONAL: L("Informational", "neutral"),
};
export const SEVERITY: Record<ComplianceSeverity, { label: string; variant: Variant }> = {
  BLOCKER: L("Blocker", "danger"),
  WARNING: L("Warning", "warning"),
  INFO: L("Info", "neutral"),
};
export const BASIS: Record<RequirementBasis, string> = {
  REGULATORY_REQUIRED: "Regulatory",
  ADVISORY: "Advisory",
  BUYER_REQUESTED: "Buyer requested",
  USER_DEFINED: "User defined",
};
export const APPLICABILITY: Record<Applicability, string> = { APPLICABLE: "Applies", NOT_APPLICABLE: "Not applicable", UNKNOWN: "Unknown — needs confirmation" };
export const COVERAGE: Record<CoverageLevel, { label: string; variant: Variant }> = {
  COMPLETE: L("Complete (curated rules)", "success"),
  PARTIAL: L("Partial", "warning"),
  UNKNOWN: L("Unknown — coverage incomplete", "danger"),
};
export const DOC_TYPE: Record<TradeDocumentType, string> = {
  COMMERCIAL_INVOICE: "Commercial invoice",
  PACKING_LIST: "Packing list",
  SHIPPING_INSTRUCTION: "Shipping instruction",
  CERTIFICATE_OF_ORIGIN: "Certificate of origin",
  PHYTOSANITARY_CERTIFICATE: "Phytosanitary certificate",
  INSPECTION_CERTIFICATE: "Inspection certificate",
  TEST_CERTIFICATE: "Test / analysis certificate",
  FUMIGATION_CERTIFICATE: "Fumigation certificate",
  INSURANCE_CERTIFICATE: "Insurance certificate",
  SHIPPING_BILL: "Shipping bill",
  BILL_OF_LADING: "Bill of lading",
  AIRWAY_BILL: "Airway bill",
  REGISTRATION_CERTIFICATE: "Registration certificate",
  PURCHASE_ORDER: "Purchase order (buyer copy)",
  PROFORMA_INVOICE: "Proforma invoice (copy)",
  CERTIFICATE: "Certificate",
  OTHER_SHIPPING_DOCUMENT: "Other shipping document",
  OTHER: "Other",
};
export const DOC_STATUS: Record<DocumentStatus, { label: string; variant: Variant }> = {
  DRAFT: L("Draft", "neutral"),
  GENERATED: L("Generated", "neutral"),
  UPLOADED: L("Uploaded", "info"),
  UNDER_REVIEW: L("Under review", "info"),
  APPROVED: L("Approved", "success"),
  REJECTED: L("Rejected", "danger"),
  ISSUED_EXTERNAL: L("Issued externally", "success"),
  EXPIRED: L("Expired", "danger"),
  SUPERSEDED: L("Superseded", "neutral"),
  ARCHIVED: L("Archived", "neutral"),
};
/** Generated vs uploaded vs external badge text. */
export const SOURCE: Record<DocumentSource, { label: string; variant: Variant }> = {
  SYSTEM_GENERATED: L("Generated by ExportPro", "info"),
  USER_UPLOADED: L("User uploaded", "neutral"),
  GOVERNMENT_ISSUED: L("External / Government", "warning"),
  CARRIER_ISSUED: L("Carrier issued", "warning"),
  INSPECTION_AGENCY: L("Inspection agency", "warning"),
  BANK: L("Bank", "warning"),
  BUYER: L("From buyer", "neutral"),
  OTHER: L("External / other", "neutral"),
};
export const PARTY: Record<ResponsibleParty, string> = {
  EXPORTER: "Exporter (you)",
  BUYER: "Buyer",
  GOVERNMENT: "Government / authority",
  CARRIER: "Carrier",
  BANK: "Bank",
  INSPECTION_AGENCY: "Inspection agency",
  CUSTOMS_BROKER: "Customs broker",
  OTHER: "Other",
};
export const AVAILABILITY: Record<DocumentAvailability, { label: string; variant: Variant }> = {
  NOT_AVAILABLE: L("Not available", "danger"),
  REQUESTED: L("Requested", "info"),
  DRAFT: L("Draft", "neutral"),
  AVAILABLE: L("Available — awaiting approval", "info"),
  APPROVED: L("Approved", "success"),
  EXPIRED: L("Expired", "danger"),
};
export const EXPIRY: Record<NonNullable<ExpiryState>, { label: string; variant: Variant }> = {
  VALID: L("Valid", "success"),
  EXPIRING_SOON: L("Expires soon", "warning"),
  EXPIRED: L("Expired", "danger"),
};


export const EXTRACTION_STATUS: Record<DocumentExtractionStatus, { label: string; variant: Variant }> = {
  PENDING: L("Pending", "neutral"),
  PROCESSING: L("Processing", "info"),
  COMPLETED: L("Extracted — review", "info"),
  PARTIAL: L("Partly extracted — review", "warning"),
  FAILED: L("Extraction failed", "danger"),
  NEEDS_REVIEW: L("Needs review", "warning"),
  CONFIRMED: L("Confirmed by reviewer", "success"),
};
export const VALIDATION_STATUS: Record<DocumentValidationStatus, { label: string; variant: Variant }> = {
  NOT_RUN: L("Not validated", "neutral"),
  PROCESSING: L("Validating", "info"),
  NEEDS_REVIEW: L("Needs review", "warning"),
  FAILED: L("Critical issues", "danger"),
  PASSED: L("No issues found", "success"),
  PASSED_WITH_WARNINGS: L("Warnings", "warning"),
  REJECTED: L("Rejected", "danger"),
  SIGNED_OFF: L("Signed off", "success"),
};
export const V_SEVERITY: Record<ValidationSeverity, { label: string; variant: Variant }> = { CRITICAL: L("Critical", "danger"), WARNING: L("Warning", "warning"), INFO: L("Info", "neutral") };
export const FINDING_STATUS: Record<ValidationFindingStatus, string> = { OPEN: "Open", ACCEPTED_DIFFERENCE: "Accepted difference", CORRECTED: "Corrected", FALSE_POSITIVE: "False positive", RESOLVED: "Resolved" };
export const CONFIDENCE: Record<ExtractionConfidence, Variant> = { HIGH: "success", MEDIUM: "info", LOW: "warning" };
export const PROVENANCE: Record<ExtractionProvenance, string> = { AI_EXTRACTED: "AI extracted", RULE_EXTRACTED: "Parser extracted", USER_CONFIRMED: "Confirmed", USER_CORRECTED: "Corrected", USER_ENTERED: "Entered manually", STRUCTURED_SOURCE: "Structured source" };
export const MISSING_STATE: Record<MissingDocumentState, { label: string; variant: Variant }> = {
  AVAILABLE: L("Available", "success"),
  MISSING_NOW: L("Missing now", "danger"),
  EXPECTED_LATER: L("Expected later", "neutral"),
  NOT_APPLICABLE: L("Not applicable", "neutral"),
  UNKNOWN: L("Unknown", "warning"),
};
export const FIELD_LABEL: Record<string, string> = {
  documentNumber: "Document no.", documentDate: "Document date", buyerName: "Buyer / importer", buyerAddress: "Buyer address", buyerCountry: "Buyer country",
  exporterName: "Exporter / shipper", exporterAddress: "Exporter address", consigneeName: "Consignee", consigneeAddress: "Consignee address", notifyParty: "Notify party",
  currency: "Currency", incoterm: "Incoterm", incotermPlace: "Incoterm place", poNumber: "PO number", quotationNumber: "Quotation no.", piNumber: "PI number", invoiceNumber: "Invoice number",
  originCountry: "Origin country", destinationCountry: "Destination country", totalAmount: "Total amount", paymentTerms: "Payment terms", deliveryTerms: "Delivery terms",
  carrier: "Carrier", vessel: "Vessel", voyage: "Voyage", containerNumbers: "Container no(s).", blNumber: "B/L number", awbNumber: "AWB number", portOfLoading: "Port of loading",
  portOfDischarge: "Port of discharge", placeOfDelivery: "Place of delivery", etd: "ETD (as written)", eta: "ETA (as written)", packageCount: "Packages", grossWeightKg: "Gross weight (kg)",
  netWeightKg: "Net weight (kg)", cargoDescription: "Cargo description", certificateNumber: "Certificate no.", certificateType: "Certificate type", issuer: "Issuer", issueDate: "Issue date",
  expiryDate: "Expiry date", hsCode: "HS code", productDescription: "Product",
  description: "Description", buyerSku: "Buyer SKU", quantity: "Quantity", unit: "Unit", unitPrice: "Unit price", total: "Line total", specification: "Specification", packaging: "Packaging",
  countryOfOrigin: "Origin", packageType: "Package type", marks: "Marks", dimensions: "Dimensions", volumeCbm: "Volume (CBM)",
};
